name: 'Delete old issues'

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: cargomedia/cleaner@main
        with:
          repository-name: 'test'
          repository-owner: 'cargomedia'
          days-before-deletion: '1625'
